import Head from "next/head";
import Image from "next/image";
import { Inconsolata } from "next/font/google";
import MainPage from "@/components/MainPage/MainPage";

const inconsolata = Inconsolata({
  subsets: ["latin"],
  weight: ["300", "600", "700", "500", "400", "900"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Do you know what's behind this?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/app.svg" />
      </Head>
      <main className={inconsolata.className}>
        <MainPage />
      </main>
    </>
  );
}
